# Generated by Django 4.1.2 on 2022-10-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccomment',
            name='cimage',
            field=models.ImageField(blank=True, null=True, upload_to='comments'),
        ),
        migrations.AlterField(
            model_name='qcomment',
            name='cimage',
            field=models.ImageField(blank=True, null=True, upload_to='comments'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qtext',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
