# Generated by Django 4.1.2 on 2022-10-14 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_ccomment_cimage_alter_qcomment_cimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ccomment',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='qcomment',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='qcomment',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RemoveField(
            model_name='ccomment',
            name='comment_id',
        ),
        migrations.AddField(
            model_name='question',
            name='student',
            field=models.ForeignKey(default=203153927, on_delete=django.db.models.deletion.PROTECT, to='api.student'),
        ),
        migrations.AlterField(
            model_name='ccomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question'),
        ),
    ]
