# Generated by Django 4.1.2 on 2022-10-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_student_id_ccomment_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccomment',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
