# Generated by Django 4.1.2 on 2022-10-14 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_ccomment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.qcomment'),
        ),
    ]
